---
abstract: 'extremely easy access to sql data'
author:
  - 'Ivan Bessarabov <ivan@bessarabov.ru>'
build_requires:
  Test::More: 0
  open: 0
  utf8: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: SQL-Easy
requires:
  Carp: 0
  DBI: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/bessarabov/SQL-Easy/issues
  homepage: https://github.com/bessarabov/SQL-Easy
  repository: https://github.com/bessarabov/SQL-Easy.git
version: 1.0.0
